"""Graphics module for ARTIFACT rendering pipeline."""

from artifact.graphics.renderer import Renderer
from artifact.graphics.primitives import (
    draw_rect,
    draw_circle,
    draw_line,
    draw_text,
    draw_image,
    fill,
    clear,
)
from artifact.graphics.compositor import DisplayCompositor
from artifact.graphics.fonts import (
    PixelFont,
    load_font,
    get_default_font,
    get_cyrillic_font,
    draw_text_bitmap,
    center_text_x,
    wrap_text,
    draw_text_centered,
)
from artifact.graphics.text_utils import (
    TextAlign,
    TextEffect,
    TextStyle,
    TextBlock,
    measure_text,
    measure_text_exact,
    calc_centered_x,
    calc_text_x,
    smart_wrap_text,
    calc_max_chars_per_line,
    calc_scale_to_fit,
    render_text_block,
    draw_centered_text,
    draw_wrapped_text,
    fit_text_in_rect,
    draw_title,
    draw_subtitle,
    draw_prompt,
    draw_main_text,
    format_lcd_text,
    truncate_lcd_text,
    calc_ticker_scroll,
)

__all__ = [
    # Renderer
    "Renderer",
    "DisplayCompositor",
    # Primitives
    "draw_rect",
    "draw_circle",
    "draw_line",
    "draw_text",
    "draw_image",
    "fill",
    "clear",
    # Fonts
    "PixelFont",
    "load_font",
    "get_default_font",
    "get_cyrillic_font",
    "draw_text_bitmap",
    "center_text_x",
    "wrap_text",
    "draw_text_centered",
    # Text utilities
    "TextAlign",
    "TextEffect",
    "TextStyle",
    "TextBlock",
    "measure_text",
    "measure_text_exact",
    "calc_centered_x",
    "calc_text_x",
    "smart_wrap_text",
    "calc_max_chars_per_line",
    "calc_scale_to_fit",
    "render_text_block",
    "draw_centered_text",
    "draw_wrapped_text",
    "fit_text_in_rect",
    "draw_title",
    "draw_subtitle",
    "draw_prompt",
    "draw_main_text",
    "format_lcd_text",
    "truncate_lcd_text",
    "calc_ticker_scroll",
]
