#!/usr/bin/env bash
# =============================================================================
# ARTIFACT Audio Setup - Maximum Nightclub Volume
# =============================================================================
# This script configures the Raspberry Pi 4 audio for maximum volume output
# through the 3.5mm headphone jack (bcm2835 Headphones).  ALSA card numbers
# are intentionally not hard-coded: the USB capture device may enumerate
# before or after the onboard output across boots.
#
# Run this:
# - At boot via systemd (artifact-audio.service)
# - Manually when audio isn't working
#
# The script:
# 1. Loads the snd-bcm2835 audio driver
# 2. Sets volume to absolute maximum (+4dB)
# 3. Unmutes all channels
# 4. Verifies audio is working
# =============================================================================

set -euo pipefail

echo "=== ARTIFACT Audio Setup ==="
echo "Configuring maximum nightclub volume..."

# -----------------------------------------------------------------------------
# 1. Load audio driver if not already loaded
# -----------------------------------------------------------------------------
echo "Loading snd-bcm2835 audio driver..."
if ! lsmod | grep -q snd_bcm2835; then
    modprobe snd-bcm2835
    sleep 1
    echo "  -> Driver loaded"
else
    echo "  -> Driver already loaded"
fi

# Resolve the stable onboard headphones card by its ALSA name.
AUDIO_CARD_INDEX="$(aplay -l | sed -nE '/Headphones/ s/^card ([0-9]+):.*/\1/p' | head -n 1)"
if [[ -z "$AUDIO_CARD_INDEX" ]]; then
    echo "ERROR: bcm2835 Headphones output was not found."
    echo "Enable dtparam=audio=on and remove the noaudio VC4 overlay option, then reboot."
    echo "Available cards:"
    aplay -l
    exit 1
fi
AUDIO_CARD_ID="$(tr -cd '[:alnum:]_-' < "/proc/asound/card${AUDIO_CARD_INDEX}/id")"
if [[ -z "$AUDIO_CARD_ID" ]]; then
    echo "ERROR: Unable to resolve stable ALSA card ID for card $AUDIO_CARD_INDEX"
    exit 1
fi
echo "  -> bcm2835 Headphones detected as card $AUDIO_CARD_INDEX ($AUDIO_CARD_ID)"

# -----------------------------------------------------------------------------
# 2. Set volume to absolute maximum (+4dB)
# -----------------------------------------------------------------------------
echo "Setting volume to maximum (+4dB)..."

# Card 2 (bcm2835 Headphones) controls:
# - numid=1: PCM Playback Volume (range: -10239 to 400, 400 = +4dB)
# - numid=2: PCM Playback Switch (on/off)

# Set PCM volume to 400 (+4dB) - the absolute maximum
amixer -c "$AUDIO_CARD_INDEX" cset numid=1 400 2>/dev/null && echo "  -> numid=1 (volume) = 400 (+4dB)" || true

# Unmute PCM
amixer -c "$AUDIO_CARD_INDEX" cset numid=2 on 2>/dev/null && echo "  -> numid=2 (switch) = on" || true

# Fallback: try named controls
amixer -c "$AUDIO_CARD_INDEX" sset PCM 100% unmute 2>/dev/null && echo "  -> PCM = 100% unmute" || true
amixer sset PCM 100% unmute 2>/dev/null || true
amixer sset Master 100% unmute 2>/dev/null || true

# -----------------------------------------------------------------------------
# 3. Set ALSA defaults to the stable card ID
# -----------------------------------------------------------------------------
echo "Setting ALSA defaults..."

# Create /etc/asound.conf if it doesn't exist or update it
cat > /etc/asound.conf << EOF
# ARTIFACT Audio Configuration
# Default to bcm2835 Headphones by stable ALSA ID. Generated by setup-audio.sh.

pcm.headphones {
    type hw
    card "$AUDIO_CARD_ID"
    device 0
}

pcm.boost {
    type softvol
    slave.pcm "headphones"
    control {
        name "Boost"
        card "$AUDIO_CARD_ID"
    }
    min_dB -51.0
    max_dB 6.0
}

pcm.!default {
    type plug
    slave.pcm "boost"
}

ctl.!default {
    type hw
    card "$AUDIO_CARD_ID"
}
EOF
echo "  -> /etc/asound.conf configured"

# -----------------------------------------------------------------------------
# 4. Ensure module loads at boot
# -----------------------------------------------------------------------------
echo "Configuring module autoload..."

# Create modules-load.d config
echo "snd-bcm2835" > /etc/modules-load.d/audio.conf
echo "  -> /etc/modules-load.d/audio.conf created"

# -----------------------------------------------------------------------------
# 5. Verify configuration
# -----------------------------------------------------------------------------
echo ""
echo "=== Audio Configuration Complete ==="
echo ""
echo "Current volume levels:"
amixer -c "$AUDIO_CARD_INDEX" sget PCM 2>/dev/null || amixer -c "$AUDIO_CARD_INDEX" contents | head -20

echo ""
echo "Available audio devices:"
aplay -l | grep -E "^card"

echo ""
echo "Testing audio output (brief beep)..."
# Generate a short 440Hz sine wave beep to verify audio works
if command -v speaker-test &> /dev/null; then
    timeout 0.5 speaker-test -D default -t sine -f 440 -l 1 2>/dev/null || true
    echo "  -> Audio test complete (if you heard a beep, audio is working!)"
else
    echo "  -> speaker-test not available, skipping audio test"
fi

echo ""
echo "=== ARTIFACT ready for maximum volume! ==="
echo "Audio device: default -> $AUDIO_CARD_ID (card $AUDIO_CARD_INDEX)"
echo "Volume: +4dB (maximum)"
